language: rust
rust:
  - stable
  - nightly
cache: cargo

addons:
  firefox: latest
  chrome: stable

install:
  - cargo uninstall wasm-pack
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo install cargo-tarpaulin
  fi

script:
  - cd core
  - cargo clean
  - cargo build
  - cargo test
  - cd ../public
  - cargo clean
  - cargo build
  - cargo test
  - wasm-pack test --firefox --headless
  - wasm-pack test --chrome  --headless
  - cd ../server
  - cargo clean
  - cargo build
  - cargo test

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cd $TRAVIS_BUILD_DIR/core
    cargo tarpaulin --out Xml --run-types Tests --run-types Doctests
    bash <(curl -s https://codecov.io/bash) -F core -y ../.codecov.yml
    cd ../public
    cargo tarpaulin --out Xml --run-types Tests --run-types Doctests
    bash <(curl -s https://codecov.io/bash) -F public -y ../.codecov.yml
    cd ../server
    cargo tarpaulin --out Xml --run-types Tests --run-types Doctests
    bash <(curl -s https://codecov.io/bash) -F server -y ../.codecov.yml
  fi
